# Generated by Django 4.2.7 on 2024-01-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ParkingApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkowner",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
        migrations.AddField(
            model_name="parkowner",
            name="password",
            field=models.CharField(default="", max_length=100),
        ),
    ]
