# Generated by Django 4.2.7 on 2024-01-13 13:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ParkingApp", "0002_parkowner_email_parkowner_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="park",
            name="no_floors",
        ),
    ]
