# Generated by Django 4.2.7 on 2024-01-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ParkingApp", "0003_remove_park_no_floors"),
    ]

    operations = [
        migrations.AddField(
            model_name="park",
            name="no_floors",
            field=models.IntegerField(default=2),
        ),
    ]
